name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '04 08 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: "This issue is stale because it has been open for 60 days with no activity. Please update or respond to this comment if you're still interested in working on this."
        stale-pr-message: "This issue is stale because it has been open for 60 days with no activity. Please update or respond to this comment if you're still interested in working on this."
        stale-issue-label: 'stale-issue'
        stale-pr-label: 'stale-pr'
        days-before-stale: 60
        days-before-close: 7
        remove-stale-when-updated: true
        debug-only: false
